### ISSUE TITLE
What's the difference between lstf and lsconntrack?

### ISSUE THREAD

**Issue by wcc526** [yuuki/lstf#22]
What's the difference between lstf and lsconntrack?

**Comment by yuuki** [comment]
The difference relies on data source for scanning.
lstf displays a snapshot of current connections scanning from /proc and netlink, on the other hand,  lsconntrack shows  connections  from the past to the present scanning from Linux conntrack, but some environments disable conntrack and conntrack has the limitation of the number of connections.
